export interface TileData {
  imageLink: string;
  description: string;
  amount: string;
  coinCost: string;
  coinproduce: string;
  indexId: string;
}
export const TILEDATA: TileData[] = [
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile--1.png',
    // imageLink: 'tiles/tile-0.png',
    // color: 'common',
    description: 'Kios Sayur',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '-1',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-0.png',
    // color: 'common',
    description: 'Kios Sayur',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '0',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-1.png',
    // imageLink: 'tiles/tile-1.png',
    // color: 'common',
    description: 'Kios Sayur',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '1',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-2.png',
    // imageLink: 'tiles/tile-2.png',
    // color: 'common',
    description: 'Kios Buah',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '2',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-3.png',
    // imageLink: 'tiles/tile-3.png',
    // color: 'common',
    description: 'Kios Makanan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '3',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-4.png',
    // imageLink: 'tiles/tile-4.png',
    // color: 'common',
    description: 'Kios Minuman',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '4',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-5.png',
    // imageLink: 'tiles/tile-5.png',
    // color: 'common',
    description: 'Kios Pakaian',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '5',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-6.png',
    // imageLink: 'tiles/tile-6.png',
    // color: 'common',
    description: 'Kios Sepatu',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '6',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-7.png',
    // imageLink: 'tiles/tile-7.png',
    // color: 'common',
    description: 'Kios Elektronik',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '7',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-8.png',
    // imageLink: 'tiles/tile-8.png',
    // color: 'common',
    description: 'Kios Buku',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '8',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-9.png',
    // imageLink: 'tiles/tile-9.png',
    // color: 'common',
    description: 'Kios Perhiasan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '9',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-10.png',
    // imageLink: 'tiles/tile-10.png',
    // color: 'common',
    description: 'Kios Mainan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '10',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-11.png',
    // imageLink: 'tiles/tile-11.png',
    // color: 'common',
    description: 'Kios Alat Tulis',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '11',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-12.png',
    // imageLink: 'tiles/tile-12.png',
    // color: 'common',
    description: 'Kios Sepeda',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '12',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-13.png',
    // imageLink: 'tiles/tile-13.png',
    // color: 'common',
    description: 'Kios Motor',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '13',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-14.png',
    // imageLink: 'tiles/tile-14.png',
    // color: 'common',
    description: 'Kios Mobil',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '14',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-15.png',
    // color: 'common',
    description: 'Kios Furniture',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '15',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-16.png',
    // color: 'common',
    description: 'Kios Perabotan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '16',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-17.png',
    // color: 'common',
    description: 'Kios Perlengkapan Bayi',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '17',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-18.png',
    // color: 'common',
    description: 'Kios Olahraga',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '18',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-19.png',
    // color: 'common',
    description: 'Kios Hewan Peliharaan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '19',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-20.png',
    // color: 'common',
    description: 'Kios Tanaman',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '20',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-21.png',
    // color: 'common',
    description: 'Kios Bunga',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '21',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-22.png',
    // color: 'common',
    description: 'Kios Kesehatan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '22',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-23.png',
    // color: 'common',
    description: 'Kios Obat',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '23',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-24.png',
    // color: 'common',
    description: 'Kios Kosmetik',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '24',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-25.png',
    // color: 'common',
    description: 'Kios Fashion',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '25',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-26.png',
    // color: 'common',
    description: 'Kios Aksesoris',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '26',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-27.png',
    // color: 'common',
    description: 'Kios Souvenir',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '27',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-28.png',
    // color: 'common',
    description: 'Kios Kerajinan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '28',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-29.png',
    // color: 'common',
    description: 'Kios Musik',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '29',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-30.png',
    // color: 'common',
    description: 'Kios Film',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '30',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-31.png',
    // color: 'common',
    description: 'Kios Game',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '31',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-32.png',
    // color: 'common',
    description: 'Kios Alat Musik',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '32',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-33.png',
    // color: 'common',
    description: 'Kios Alat Olahraga',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '33',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-34.png',
    // color: 'common',
    description: 'Kios Alat Elektronik',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '34',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-35.png',
    // color: 'common',
    description: 'Kios Alat Komputer',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '35',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-36.png',
    // color: 'common',
    description: 'Kios Alat Tulis Kantor',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '36',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-37.png',
    // color: 'common',
    description: 'Kios Alat Bangunan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '37',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-38.png',
    // color: 'common',
    description: 'Kios Alat Kendaraan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '38',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-39.png',
    // color: 'common',
    description: 'Kios Alat Pertanian',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '39',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-40.png',
    // color: 'common',
    description: 'Kios Alat Perikanan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '40',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-41.png',
    // color: 'common',
    description: 'Kios Alat Peternakan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '41',
  },
  {
    imageLink: 'https://trelel129.github.io/asset/tiles/tile-42.png',
    // color: 'common',
    description: 'Kios Alat Perkebunan',
    amount: '1',
    coinCost: '10',
    coinproduce: '1',
    indexId: '42',
  },
];
