export interface TileData {
  image: string;
  name: string;
  amount: string;
  price: string;
  coinproduce: string;
  id: string;
}
export const TILEDATA: TileData[] = [
  {
    image: 'https://trelel129.github.io/asset/tile/tile--1.png',
    // color: 'common',
    name: 'Kios Sayur',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '1',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-0.png',
    // color: 'common',
    name: 'Kios Sayur',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '1',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-1.png',
    // color: 'common',
    name: 'Kios Sayur',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '1',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-2.png',
    // color: 'common',
    name: 'Kios Buah',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '2',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-3.png',
    // color: 'common',
    name: 'Kios Makanan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '3',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-4.png',
    // color: 'common',
    name: 'Kios Minuman',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '4',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-5.png',
    // color: 'common',
    name: 'Kios Pakaian',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '5',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-6.png',
    // color: 'common',
    name: 'Kios Sepatu',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '6',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-7.png',
    // color: 'common',
    name: 'Kios Elektronik',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '7',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-8.png',
    // color: 'common',
    name: 'Kios Buku',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '8',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-9.png',
    // color: 'common',
    name: 'Kios Perhiasan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '9',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-10.png',
    // color: 'common',
    name: 'Kios Mainan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '10',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-11.png',
    // color: 'common',
    name: 'Kios Alat Tulis',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '11',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-12.png',
    // color: 'common',
    name: 'Kios Sepeda',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '12',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-13.png',
    // color: 'common',
    name: 'Kios Motor',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '13',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-14.png',
    // color: 'common',
    name: 'Kios Mobil',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '14',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-15.png',
    // color: 'common',
    name: 'Kios Furniture',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '15',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-16.png',
    // color: 'common',
    name: 'Kios Perabotan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '16',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-17.png',
    // color: 'common',
    name: 'Kios Perlengkapan Bayi',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '17',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-18.png',
    // color: 'common',
    name: 'Kios Olahraga',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '18',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-19.png',
    // color: 'common',
    name: 'Kios Hewan Peliharaan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '19',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-20.png',
    // color: 'common',
    name: 'Kios Tanaman',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '20',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-21.png',
    // color: 'common',
    name: 'Kios Bunga',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '21',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-22.png',
    // color: 'common',
    name: 'Kios Kesehatan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '22',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-23.png',
    // color: 'common',
    name: 'Kios Obat',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '23',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-24.png',
    // color: 'common',
    name: 'Kios Kosmetik',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '24',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-25.png',
    // color: 'common',
    name: 'Kios Fashion',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '25',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-26.png',
    // color: 'common',
    name: 'Kios Aksesoris',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '26',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-27.png',
    // color: 'common',
    name: 'Kios Souvenir',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '27',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-28.png',
    // color: 'common',
    name: 'Kios Kerajinan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '28',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-29.png',
    // color: 'common',
    name: 'Kios Musik',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '29',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-30.png',
    // color: 'common',
    name: 'Kios Film',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '30',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-31.png',
    // color: 'common',
    name: 'Kios Game',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '31',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-32.png',
    // color: 'common',
    name: 'Kios Alat Musik',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '32',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-33.png',
    // color: 'common',
    name: 'Kios Alat Olahraga',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '33',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-34.png',
    // color: 'common',
    name: 'Kios Alat Elektronik',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '34',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-35.png',
    // color: 'common',
    name: 'Kios Alat Komputer',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '35',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-36.png',
    // color: 'common',
    name: 'Kios Alat Tulis Kantor',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '36',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-37.png',
    // color: 'common',
    name: 'Kios Alat Bangunan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '37',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-38.png',
    // color: 'common',
    name: 'Kios Alat Kendaraan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '38',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-39.png',
    // color: 'common',
    name: 'Kios Alat Pertanian',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '39',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-40.png',
    // color: 'common',
    name: 'Kios Alat Perikanan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '40',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-41.png',
    // color: 'common',
    name: 'Kios Alat Peternakan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '41',
  },
  {
    image: 'https://trelel129.github.io/asset/tile/tile-42.png',
    // color: 'common',
    name: 'Kios Alat Perkebunan',
    amount: '1',
    price: '10',
    coinproduce: '1',
    id: '42',
  },
];
